# Generated by Django 5.0.2 on 2024-02-16 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
