# Generated by Django 5.0.2 on 2024-02-15 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_date_board_likes_board_reivews_board_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='reivews',
            new_name='reviews',
        ),
    ]
